### ISSUE TITLE
Model-Explorer: Task list of suggestions and problems #enhancement #gui

### ISSUE THREAD

**Issue by NoxMortem** [UrsZeidler/shr5rcp#107]
I strongly suggest, if possible with emf, to clean up the context menu.The GUI is very cluttered and many semantics are unclear.

Suggested changes and list of questions:

- [ ] Rename "shr5Resources" to "Resources"
- [x] Rename "Spieler mgmnt" to "Spieler"
- [x] Rename "Spieler Charakter" to "SC" and the english version to "PC"
- [x] Rename "Nicht Spieler Charakter" to "NSC" and the english version to "NPC"
- [x] Rename "Persona Eigenschaft" to "Positve Quality" for positive qualities
- [x] Rename "Persona Eigenschaft" to "Negative Quality" for negative qualities
- [x] Rename "Mudan" to "Mundane" (typo)
- [x] Rename "Lizenz Traeger" to "Lizenzhalter"
- [x] Rename "Overdead" to "Overflow"
- [x] Rename "Verbrachtes Edge" to "Verbrauchtes Edge"
- [x] Rename "Grunt Member" to "Grunt Type" (as this is actually a group of X of a kind)
- [x] Rename "Shr List all" to "All" - or if the Type of each object is required to be displayed, rename "Shr List" to "List" which would result in "List all".
- [x] Add ":" between type of nodes and name. Example: "Shr List: Sourcebooks" instead of "Shr List Sourcebook". This clarifies if the node is of type "Shr List" or of type "Shr" or of type "Shr List Sourcebooks" (with an empty name)
- [x] Node Editor-> Image "change" button. The resource location text field should have a file open dialogue option. The search box is handy, but no intuitive for default users.
- [x] Node Editor-> Image "change" button dialogue: Add a remove image button. Currently removal is only possible with not selecting an option (which is counterintuitive as well). Currently removal is possible when the .project file is selected
- [ ] Add a walktrough for the provided default project for non Shr List nodes an *why* they are where they are. (I would do this for you but i am completly unsure how the model really works in many cases) [Urgent! This would help me a lot to create/test the program, could not find this under: https://github.com/UrsZeidler/shr5rcp/wiki/shr5-model]
  - [x] Spieler mgmt my player (What does this node do?)
  - [x] Spieler Gruppe player group (Are there supposed to be more than 1 type of player groups? Maybe better structure by "PC" and "NPC")
  - [x] Why has each character a child node with the same editor. (Spieler Charakter Ki Adept Gunter von Kintzel) -> (Ki Adept Gunter von Kintzel). Would it be possible to pull the child nodes one level up in the hierarchy?
  - [x] The attribute box as a whole should be collapsable not each part of it. It makes not much sense to just collapse one box - it does make sense to collapse all four together.
  - [x] Hierarchical Nodes which structure skills into skills and equipment into equipment, etc. would help a lot. The editor of this node could just provide an overview. Especially a node grouping the charater advancement would be very helpful. This would also mean that the context menu for a Character is cleaned up because you could only "Add Drones" to the "Drone" node (etc. for all the other 30 nodes).
  - [x] What is the "Shr5 Generator Gu COMMITED" node?
  - [x] Does the Spieler mgmnt my player node need all the generators? (I have read the wiki about it but still am unsure)
  - [ ] How does the relationship between Parent->Childs work? There are no visible cues how this relationship works. Fo example: if I export an character and try to import it into the shr5Resource directly this does and should not work but the only way to find this out was trying it out.
-  [x] What is a "Grund Group" (There are no default test values, i could not assign a Grunt Group to a new script and could not find out what it should be)
- [x] Why am i only able to add "Player Characters" to a "Grunt Team" (could be a bug?)
- [x] License should be linkable objects like 
- [x] The default text instead of [null] should be very often "none"
- [ ] Charakter Gruppe non player group->nicht Spieler Character Mudan Persona Thugs & mouth breathers->Lizenz Gun Licence->Lizenz Traeger: Seems to be linked wrongly. There are 3 Sin's listed and i could not find them for this NPC.
- [x] Add a search feature (this would help to find erronous texts and correct them), it does not even have to be fast and even just searching the node name would be ok for the beginning.
- [ ] I do think the differentiation between PC/NPC/Grunt only complicates things. A character is always a "character" in Shadowrun and I do think it would be better to only use one type of characters and difference between player and non player only for the purpose of structuring (where the GM should be able to generate groups of any types he want (city/location/race) and maybe assign character multiple times (multiple categories). The differentiation seems to be important only for the web interface and which characters are selectable. At least i was not able to see the benefit of the more complicated system.
- [ ] Exactly the same as for the types of characters i also would remove the whole differentiation for "group" nodes. It makes the context menus more complicated and i can not see any benefits.
- [x] I am able to add mgmt nodes endlessly inside of a script. Not a bug but senseless stuff should be prevented (I think stuff like this deserves its own issue and i might create one if i have gathered enough knowledge about the program and how it does work). Does a mgmt node inside of a script makes any sense at all?
- [x] I can add "All Teams" nodes and for each type a node" - they do not seem to have any differences. One of those therefore should be removed.
- [x] The character editor has a "{}" text inside of it (inside of the team) The whole text area lacks any labels and explanations.
- [x] Add "Feature dialogue" has various mislabelings, probably copy paste errors: When adding characters to a team it says "Zauber auswählen - Shr List", it has a nuyen counter on the bottom left, it states "Feature" but should actually have a labeling like "Selected", it has a button "show only list items" which does not really state what it does show as all options vanish
- [x] What does the "Skript History" node do?
- [x] Creating a fight script is WAAAAAAAAAY too complicated. Instead of just saying "combat" and adding the characters for each side you have to (at least it looks like that):
  * Create a "Schergen Gruppe"
  * Create NSC
  * Add Grunt Member
  * Assign each Grunt Member the correct NSc
  * Set the number of members for this Grunt Member group
  * Create a Player Character group
  * Create the characters
  * Create a Team
  * Add the characters to the team
  * Fail with multiple null pointers when clicking right click Grunt Member on the Grunt Team in the script (error log in its own issue)

Possibly more to follow
